the update chart

diff --git a/templates/tests/test-connection.yaml b/templates/tests/test-connection.yaml
--- a/templates/tests/test-connection.yaml
+++ b/templates/tests/test-connection.yaml
@@ -1,15 +1,31 @@
 apiVersion: v1
 kind: Pod
 metadata:
-  name: "{{ include "liferay-helm.fullname" . }}-test-connection"
+  name: "{{ include "liferay.fullname" . }}-test-connection"
   labels:
-    {{- include "liferay-helm.labels" . | nindent 4 }}
+    {{- include "liferay.labels" . | nindent 4 }}
   annotations:
     "helm.sh/hook": test
 spec:
   containers:
-    - name: wget
-      image: busybox
-      command: ['wget']
-      args: ['{{ include "liferay-helm.fullname" . }}:{{ .Values.service.port }}']
+    - name: test-connection
+      image: busybox:latest
+      command: ["/bin/sh","-c"]
+      args:
+        - |
+          trap 'echo "Received signal to Terminate"; exit 0' SIGINT SIGTERM
+          START=$(date +%s)
+
+          # Only wait for 5 minutes and then fail
+          until nc -vz -w 2 {{ include "liferay.fullname" . }} {{ .Values.service.port }}; do
+            NOW=$(date +%s)
+            SPAN=$(($NOW - $START))
+            if [ $SPAN -gt 300 ]; then
+              echo "DXP Service did not arrive within expected time (5 mins)."
+              exit 1
+            fi
+            echo "Waiting for DXP service"
+            sleep 2
+          done
   restartPolicy: Never
+  serviceAccountName: {{ include "liferay.serviceAccountName" . }}
